Repository jazzband/djangorestframework-simplejwt, pull requests merged in 2021-10, with the labels that each got.

#459 updated import list
  docs/settings.rst
Labels: docs, hacktoberest-accepted

#306 Add blacklist view to log out users
  rest_framework_simplejwt/serializers.py
  rest_framework_simplejwt/views.py
  tests/test_serializers.py
  tests/test_views.py
  tests/urls.py
Labels: enhancement, hacktoberest-accepted

#192 Add "iat" claim to token
  rest_framework_simplejwt/serializers.py
  rest_framework_simplejwt/tokens.py
  tests/test_tokens.py
Labels: enhancement, hacktoberest-accepted

#440 Add docs about TOKEN_USER_CLASS
  docs/settings.rst
Labels: docs

#450 Verify should check if token_blacklist installed
  rest_framework_simplejwt/serializers.py
Labels: bug
