Repository jazzband/djangorestframework-simplejwt, pull requests merged in 2021-12, with the labels that each got.

#487 Set default verifying key to empty str
  rest_framework_simplejwt/backends.py
  rest_framework_simplejwt/settings.py
Labels: bug, needs investigation

#494 Set up .readthedocs.yml
  .readthedocs.yml
Labels: bug

#478 Create .pre-commit-config.yaml
  .isort.cfg
  .pre-commit-config.yaml
  docs/conf.py
  rest_framework_simplejwt/authentication.py
  rest_framework_simplejwt/backends.py
  rest_framework_simplejwt/compat.py
  rest_framework_simplejwt/exceptions.py
  rest_framework_simplejwt/models.py
  rest_framework_simplejwt/serializers.py
  rest_framework_simplejwt/settings.py
  rest_framework_simplejwt/token_blacklist/__init__.py
  rest_framework_simplejwt/token_blacklist/admin.py
  rest_framework_simplejwt/token_blacklist/apps.py
  rest_framework_simplejwt/token_blacklist/management/commands/flushexpiredtokens.py
  rest_framework_simplejwt/token_blacklist/migrations/0001_initial.py
  rest_framework_simplejwt/token_blacklist/migrations/0002_outstandingtoken_jti_hex.py
  rest_framework_simplejwt/token_blacklist/migrations/0003_auto_20171017_2007.py
  rest_framework_simplejwt/token_blacklist/migrations/0004_auto_20171017_2013.py
  rest_framework_simplejwt/token_blacklist/migrations/0005_remove_outstandingtoken_jti.py
  rest_framework_simplejwt/token_blacklist/migrations/0006_auto_20171017_2113.py
  rest_framework_simplejwt/token_blacklist/migrations/0007_auto_20171017_2214.py
  rest_framework_simplejwt/token_blacklist/migrations/0008_migrate_to_bigautofield.py
  rest_framework_simplejwt/token_blacklist/migrations/0010_fix_migrate_to_bigautofield.py
  rest_framework_simplejwt/token_blacklist/migrations/0011_linearizes_history.py
  rest_framework_simplejwt/token_blacklist/models.py
  rest_framework_simplejwt/tokens.py
  rest_framework_simplejwt/views.py
  setup.py
  tests/conftest.py
  tests/test_authentication.py
  tests/test_backends.py
  tests/test_integration.py
  tests/test_models.py
  tests/test_serializers.py
  tests/test_token_blacklist.py
  tests/test_tokens.py
  tests/test_utils.py
  tests/test_views.py
  tests/urls.py
  tests/utils.py
  tests/views.py
  tox.ini
Labels: enhancement
