Repository jazzband/djangorestframework-simplejwt, pull requests merged in 2022-01, with the labels that each got.

#501 Added Korean translations
  rest_framework_simplejwt/locale/ko_KR/LC_MESSAGES/django.mo
  rest_framework_simplejwt/locale/ko_KR/LC_MESSAGES/django.po
Labels: enhancement

#502 Remove .mo in .gitignore
  .gitignore
Labels: bug

#504 Fix RTD config to install setup.py
  .readthedocs.yml
Labels: bug

#505 Add missing integration instructions for drf-yasg
  docs/drf_yasg_integration.rst
Labels: docs

#516 Stop deleting blacklist on user delete
  rest_framework_simplejwt/token_blacklist/migrations/0012_alter_outstandingtoken_user.py
  rest_framework_simplejwt/token_blacklist/models.py
  tests/test_token_blacklist.py
Labels: bug

#520 Enable ECDSA algorithms supported by PyJWT
  rest_framework_simplejwt/backends.py
  tests/keys.py
  tests/test_backends.py
Labels: enhancement
