Repository jazzband/djangorestframework-simplejwt, pull requests merged in 2022-02, with the labels that each got.

#521 Make the token serializer configurable
  rest_framework_simplejwt/settings.py
  rest_framework_simplejwt/views.py
Labels: enhancement

#526 Update translation files
  rest_framework_simplejwt/locale/cs/LC_MESSAGES/django.po
  rest_framework_simplejwt/locale/de_CH/LC_MESSAGES/django.po
  rest_framework_simplejwt/locale/es/LC_MESSAGES/django.mo
  rest_framework_simplejwt/locale/es/LC_MESSAGES/django.po
  rest_framework_simplejwt/locale/es_AR/LC_MESSAGES/django.po
  rest_framework_simplejwt/locale/es_CL/LC_MESSAGES/django.po
  rest_framework_simplejwt/locale/fa_IR/LC_MESSAGES/django.po
  rest_framework_simplejwt/locale/fr/LC_MESSAGES/django.po
  rest_framework_simplejwt/locale/id_ID/LC_MESSAGES/django.po
  rest_framework_simplejwt/locale/it_IT/LC_MESSAGES/django.po
  rest_framework_simplejwt/locale/ko_KR/LC_MESSAGES/django.po
  rest_framework_simplejwt/locale/nl_NL/LC_MESSAGES/django.po
  rest_framework_simplejwt/locale/pl_PL/LC_MESSAGES/django.po
  rest_framework_simplejwt/locale/pt_BR/LC_MESSAGES/django.po
  rest_framework_simplejwt/locale/ru_RU/LC_MESSAGES/django.po
  rest_framework_simplejwt/locale/tr/LC_MESSAGES/django.po
  rest_framework_simplejwt/locale/uk_UA/LC_MESSAGES/django.po
  rest_framework_simplejwt/locale/zh_Hans/LC_MESSAGES/django.po
Labels: docs

#529 Allow overriding access token class
  rest_framework_simplejwt/tokens.py
Labels: enhancement

#458 Consider leeway when checking expiry
  rest_framework_simplejwt/tokens.py
  tests/test_tokens.py
Labels: bug

#456 Add locale checker to CI
  .github/workflows/i18n.yml
  .github/workflows/release.yml
  scripts/i18n_updater.py
Labels: enhancement

#538 Fix i18n CI
  .github/workflows/i18n.yml
Labels: bug, enhancement
