Repository jazzband/djangorestframework-simplejwt, pull requests merged in 2022-04, with the labels that each got.

#555 Change from git protocol to https protocol
  .pre-commit-config.yaml
Labels: bug

#554 Fix leeway type error
  rest_framework_simplejwt/backends.py
  rest_framework_simplejwt/locale/cs/LC_MESSAGES/django.po
  rest_framework_simplejwt/locale/de_CH/LC_MESSAGES/django.po
  rest_framework_simplejwt/locale/es/LC_MESSAGES/django.po
  rest_framework_simplejwt/locale/es_AR/LC_MESSAGES/django.po
  rest_framework_simplejwt/locale/es_CL/LC_MESSAGES/django.po
  rest_framework_simplejwt/locale/fa_IR/LC_MESSAGES/django.po
  rest_framework_simplejwt/locale/fr/LC_MESSAGES/django.po
  rest_framework_simplejwt/locale/id_ID/LC_MESSAGES/django.po
  rest_framework_simplejwt/locale/it_IT/LC_MESSAGES/django.po
  rest_framework_simplejwt/locale/ko_KR/LC_MESSAGES/django.mo
  rest_framework_simplejwt/locale/ko_KR/LC_MESSAGES/django.po
  rest_framework_simplejwt/locale/nl_NL/LC_MESSAGES/django.po
  rest_framework_simplejwt/locale/pl_PL/LC_MESSAGES/django.po
  rest_framework_simplejwt/locale/pt_BR/LC_MESSAGES/django.po
  rest_framework_simplejwt/locale/ru_RU/LC_MESSAGES/django.po
  rest_framework_simplejwt/locale/tr/LC_MESSAGES/django.po
  rest_framework_simplejwt/locale/uk_UA/LC_MESSAGES/django.po
  rest_framework_simplejwt/locale/zh_Hans/LC_MESSAGES/django.po
  rest_framework_simplejwt/tokens.py
  tests/test_tokens.py
Labels: bug

#559 chore(ci): add informational Codecov status checks
  codecov.yml
Labels: enhancement

#561 Update JWTStatelessUserAuthentication docs
  docs/stateless_user_authentication.rst
Labels: docs
