Repository jazzband/djangorestframework-simplejwt, pull requests merged in 2023-12, with the labels that each got.

#725 Update settings.rst
  docs/settings.rst
Labels: docs

#769 Fix tests
  rest_framework_simplejwt/utils.py
  tests/test_init.py
  tests/test_utils.py
Labels: bug, enhancement

#770 Add pull request write permission to i18n updater
  .github/workflows/i18n.yml
Labels: enhancement
